name: Build Control Center Mod

on:
  push:
  pull_request:

jobs:
  build:
    name: Rebuild modded APK
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Rebuild APK with apktool
        run: |
          mkdir -p artifacts
          java -jar apktool_2.12.1.jar b controlcenter_mod -o artifacts/ControlCenter15-mod.apk

      - name: Upload rebuilt APK
        uses: actions/upload-artifact@v4
        with:
          name: ControlCenter15-mod
          path: artifacts/ControlCenter15-mod.apk
